package component-test:wit-protocol;

interface host {
  resource my-res {}
  my-func: func() -> option<my-res>;
}

interface guest {
  run: func();
}

world guest-world {
  import host;
  export guest;
}
